<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Judgehost extends \App\Entity\Judgehost implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Judgehost' . "\0" . 'judgehostid', '' . "\0" . 'App\\Entity\\Judgehost' . "\0" . 'hostname', '' . "\0" . 'App\\Entity\\Judgehost' . "\0" . 'enabled', '' . "\0" . 'App\\Entity\\Judgehost' . "\0" . 'polltime', '' . "\0" . 'App\\Entity\\Judgehost' . "\0" . 'judgetasks', '' . "\0" . 'App\\Entity\\Judgehost' . "\0" . 'hidden'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Judgehost' . "\0" . 'judgehostid', '' . "\0" . 'App\\Entity\\Judgehost' . "\0" . 'hostname', '' . "\0" . 'App\\Entity\\Judgehost' . "\0" . 'enabled', '' . "\0" . 'App\\Entity\\Judgehost' . "\0" . 'polltime', '' . "\0" . 'App\\Entity\\Judgehost' . "\0" . 'judgetasks', '' . "\0" . 'App\\Entity\\Judgehost' . "\0" . 'hidden'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Judgehost $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getJudgehostid(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getJudgehostid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJudgehostid', []);

        return parent::getJudgehostid();
    }

    /**
     * {@inheritDoc}
     */
    public function setHostname(string $hostname): \App\Entity\Judgehost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHostname', [$hostname]);

        return parent::setHostname($hostname);
    }

    /**
     * {@inheritDoc}
     */
    public function getHostname(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHostname', []);

        return parent::getHostname();
    }

    /**
     * {@inheritDoc}
     */
    public function getShortDescription(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShortDescription', []);

        return parent::getShortDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnabled(bool $enabled): \App\Entity\Judgehost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnabled', [$enabled]);

        return parent::setEnabled($enabled);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnabled(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnabled', []);

        return parent::getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function setPolltime($polltime): \App\Entity\Judgehost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPolltime', [$polltime]);

        return parent::setPolltime($polltime);
    }

    /**
     * {@inheritDoc}
     */
    public function getPolltime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPolltime', []);

        return parent::getPolltime();
    }

    /**
     * {@inheritDoc}
     */
    public function addJudgeTask(\App\Entity\JudgeTask $judgeTask): \App\Entity\Judgehost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addJudgeTask', [$judgeTask]);

        return parent::addJudgeTask($judgeTask);
    }

    /**
     * {@inheritDoc}
     */
    public function removeJudgeTask(\App\Entity\JudgeTask $judgeTask): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeJudgeTask', [$judgeTask]);

        parent::removeJudgeTask($judgeTask);
    }

    /**
     * {@inheritDoc}
     */
    public function getJudgeTasks(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJudgeTasks', []);

        return parent::getJudgeTasks();
    }

    /**
     * {@inheritDoc}
     */
    public function setHidden(bool $hidden): \App\Entity\Judgehost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHidden', [$hidden]);

        return parent::setHidden($hidden);
    }

    /**
     * {@inheritDoc}
     */
    public function getHidden(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHidden', []);

        return parent::getHidden();
    }

}
