<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ExternalRun extends \App\Entity\ExternalRun implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\ExternalRun' . "\0" . 'extrunid', 'externalid', '' . "\0" . 'App\\Entity\\ExternalRun' . "\0" . 'result', '' . "\0" . 'App\\Entity\\ExternalRun' . "\0" . 'endtime', '' . "\0" . 'App\\Entity\\ExternalRun' . "\0" . 'runtime', '' . "\0" . 'App\\Entity\\ExternalRun' . "\0" . 'external_judgement', '' . "\0" . 'App\\Entity\\ExternalRun' . "\0" . 'testcase', '' . "\0" . 'App\\Entity\\ExternalRun' . "\0" . 'contest'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\ExternalRun' . "\0" . 'extrunid', 'externalid', '' . "\0" . 'App\\Entity\\ExternalRun' . "\0" . 'result', '' . "\0" . 'App\\Entity\\ExternalRun' . "\0" . 'endtime', '' . "\0" . 'App\\Entity\\ExternalRun' . "\0" . 'runtime', '' . "\0" . 'App\\Entity\\ExternalRun' . "\0" . 'external_judgement', '' . "\0" . 'App\\Entity\\ExternalRun' . "\0" . 'testcase', '' . "\0" . 'App\\Entity\\ExternalRun' . "\0" . 'contest'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ExternalRun $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getExtrunid(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getExtrunid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtrunid', []);

        return parent::getExtrunid();
    }

    /**
     * {@inheritDoc}
     */
    public function setExternalid(string $externalid): \App\Entity\ExternalRun
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExternalid', [$externalid]);

        return parent::setExternalid($externalid);
    }

    /**
     * {@inheritDoc}
     */
    public function getExternalid(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExternalid', []);

        return parent::getExternalid();
    }

    /**
     * {@inheritDoc}
     */
    public function setResult(string $result): \App\Entity\ExternalRun
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResult', [$result]);

        return parent::setResult($result);
    }

    /**
     * {@inheritDoc}
     */
    public function getResult(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResult', []);

        return parent::getResult();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndtime($endtime): \App\Entity\ExternalRun
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndtime', [$endtime]);

        return parent::setEndtime($endtime);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndtime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndtime', []);

        return parent::getEndtime();
    }

    /**
     * {@inheritDoc}
     */
    public function setRuntime(float $runtime): \App\Entity\ExternalRun
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRuntime', [$runtime]);

        return parent::setRuntime($runtime);
    }

    /**
     * {@inheritDoc}
     */
    public function getRuntime(): float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRuntime', []);

        return parent::getRuntime();
    }

    /**
     * {@inheritDoc}
     */
    public function setExternalJudgement(\App\Entity\ExternalJudgement $externalJudgement): \App\Entity\ExternalRun
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExternalJudgement', [$externalJudgement]);

        return parent::setExternalJudgement($externalJudgement);
    }

    /**
     * {@inheritDoc}
     */
    public function getExternalJudgement(): \App\Entity\ExternalJudgement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExternalJudgement', []);

        return parent::getExternalJudgement();
    }

    /**
     * {@inheritDoc}
     */
    public function setTestcase(\App\Entity\Testcase $testcase): \App\Entity\ExternalRun
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTestcase', [$testcase]);

        return parent::setTestcase($testcase);
    }

    /**
     * {@inheritDoc}
     */
    public function getTestcase(): \App\Entity\Testcase
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTestcase', []);

        return parent::getTestcase();
    }

    /**
     * {@inheritDoc}
     */
    public function setContest(\App\Entity\Contest $contest = NULL): \App\Entity\ExternalRun
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContest', [$contest]);

        return parent::setContest($contest);
    }

    /**
     * {@inheritDoc}
     */
    public function getContest(): \App\Entity\Contest
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContest', []);

        return parent::getContest();
    }

}
