<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class RankCache extends \App\Entity\RankCache implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\RankCache' . "\0" . 'points_restricted', '' . "\0" . 'App\\Entity\\RankCache' . "\0" . 'totaltime_restricted', '' . "\0" . 'App\\Entity\\RankCache' . "\0" . 'points_public', '' . "\0" . 'App\\Entity\\RankCache' . "\0" . 'totaltime_public', '' . "\0" . 'App\\Entity\\RankCache' . "\0" . 'contest', '' . "\0" . 'App\\Entity\\RankCache' . "\0" . 'team'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\RankCache' . "\0" . 'points_restricted', '' . "\0" . 'App\\Entity\\RankCache' . "\0" . 'totaltime_restricted', '' . "\0" . 'App\\Entity\\RankCache' . "\0" . 'points_public', '' . "\0" . 'App\\Entity\\RankCache' . "\0" . 'totaltime_public', '' . "\0" . 'App\\Entity\\RankCache' . "\0" . 'contest', '' . "\0" . 'App\\Entity\\RankCache' . "\0" . 'team'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (RankCache $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setPointsRestricted(int $pointsRestricted): \App\Entity\RankCache
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPointsRestricted', [$pointsRestricted]);

        return parent::setPointsRestricted($pointsRestricted);
    }

    /**
     * {@inheritDoc}
     */
    public function getPointsRestricted(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPointsRestricted', []);

        return parent::getPointsRestricted();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotaltimeRestricted(int $totaltimeRestricted): \App\Entity\RankCache
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotaltimeRestricted', [$totaltimeRestricted]);

        return parent::setTotaltimeRestricted($totaltimeRestricted);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotaltimeRestricted(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotaltimeRestricted', []);

        return parent::getTotaltimeRestricted();
    }

    /**
     * {@inheritDoc}
     */
    public function setPointsPublic(int $pointsPublic): \App\Entity\RankCache
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPointsPublic', [$pointsPublic]);

        return parent::setPointsPublic($pointsPublic);
    }

    /**
     * {@inheritDoc}
     */
    public function getPointsPublic(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPointsPublic', []);

        return parent::getPointsPublic();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotaltimePublic(int $totaltimePublic): \App\Entity\RankCache
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotaltimePublic', [$totaltimePublic]);

        return parent::setTotaltimePublic($totaltimePublic);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotaltimePublic(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotaltimePublic', []);

        return parent::getTotaltimePublic();
    }

    /**
     * {@inheritDoc}
     */
    public function setContest(\App\Entity\Contest $contest = NULL): \App\Entity\RankCache
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContest', [$contest]);

        return parent::setContest($contest);
    }

    /**
     * {@inheritDoc}
     */
    public function getContest(): \App\Entity\Contest
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContest', []);

        return parent::getContest();
    }

    /**
     * {@inheritDoc}
     */
    public function setTeam(\App\Entity\Team $team = NULL): \App\Entity\RankCache
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTeam', [$team]);

        return parent::setTeam($team);
    }

    /**
     * {@inheritDoc}
     */
    public function getTeam(): \App\Entity\Team
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTeam', []);

        return parent::getTeam();
    }

}
