<?php

namespace ContainerU4tLbsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FAUBePService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.F_AUBeP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.F_AUBeP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'violations' => ['privates', '.errored..service_locator.F_AUBeP.Symfony\\Component\\Validator\\ConstraintViolationListInterface', NULL, 'Cannot autowire service ".service_locator.F_AUBeP": it references interface "Symfony\\Component\\Validator\\ConstraintViolationListInterface" but no such service exists. Did you create a class that implements this interface?'],
        ], [
            'violations' => 'Symfony\\Component\\Validator\\ConstraintViolationListInterface',
        ]);
    }
}
