<?php

namespace ContainerU4tLbsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_E0Dj3BTService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.E0Dj3BT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.E0Dj3BT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'contest' => ['privates', '.errored..service_locator.E0Dj3BT.App\\Entity\\Contest', NULL, 'Cannot autowire service ".service_locator.E0Dj3BT": it references class "App\\Entity\\Contest" but no such service exists.'],
            'run' => ['privates', '.errored..service_locator.E0Dj3BT.App\\Entity\\JudgingRun', NULL, 'Cannot autowire service ".service_locator.E0Dj3BT": it references class "App\\Entity\\JudgingRun" but no such service exists.'],
            'submission' => ['privates', '.errored..service_locator.E0Dj3BT.App\\Entity\\Submission', NULL, 'Cannot autowire service ".service_locator.E0Dj3BT": it references class "App\\Entity\\Submission" but no such service exists.'],
        ], [
            'contest' => 'App\\Entity\\Contest',
            'run' => 'App\\Entity\\JudgingRun',
            'submission' => 'App\\Entity\\Submission',
        ]);
    }
}
