<?php

namespace ContainerU4tLbsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Crql0YService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.Crql0_Y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Crql0_Y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'team' => ['privates', '.errored..service_locator.Crql0_Y.App\\Entity\\Team', NULL, 'Cannot autowire service ".service_locator.Crql0_Y": it references class "App\\Entity\\Team" but no such service exists.'],
        ], [
            'team' => 'App\\Entity\\Team',
        ]);
    }
}
