<?php

namespace ContainerU4tLbsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JCKJ3ITService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.jCKJ3IT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jCKJ3IT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'submissionService' => ['privates', 'App\\Service\\SubmissionService', 'getSubmissionServiceService', true],
        ], [
            'submissionService' => 'App\\Service\\SubmissionService',
        ]);
    }
}
