<?php

namespace ContainerU4tLbsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UvovWc4Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.UvovWc4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UvovWc4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'externalJudgement' => ['privates', '.errored..service_locator.UvovWc4.App\\Entity\\ExternalJudgement', NULL, 'Cannot autowire service ".service_locator.UvovWc4": it references class "App\\Entity\\ExternalJudgement" but no such service exists.'],
        ], [
            'externalJudgement' => 'App\\Entity\\ExternalJudgement',
        ]);
    }
}
