<?php

namespace ContainerU4tLbsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AS9XuovService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.AS9Xuov' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AS9Xuov'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'logsDir' => ['privates', '.value._URn8Zd', 'get_Value_URn8ZdService', true],
            'projectDir' => ['privates', '.value.zrvvYJt', 'get_Value_ZrvvYJtService', true],
        ], [
            'logsDir' => '?',
            'projectDir' => '?',
        ]);
    }
}
