<?php

namespace ContainerU4tLbsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Container_Private_TwigService extends App_KernelProdContainer
{
    /*
     * Gets the public '.container.private.twig' shared service.
     *
     * @return \Twig\Environment
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/lib/vendor/twig/twig/src/Cache/CacheInterface.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/twig/twig/src/Cache/FilesystemCache.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/twig/twig/src/Extension/ExtensionInterface.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/twig/twig/src/Extension/AbstractExtension.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/twig/twig/src/Extension/CoreExtension.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/twig/twig/src/Extension/EscaperExtension.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/twig/twig/src/Extension/OptimizerExtension.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/twig/twig/src/Extension/StagingExtension.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/twig/twig/src/ExtensionSet.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/twig/twig/src/Template.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/twig/twig/src/TemplateWrapper.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/twig/twig/src/Environment.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/twig/twig/src/Loader/LoaderInterface.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/twig/twig/src/Loader/FilesystemLoader.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/twig-bridge/Extension/CsrfExtension.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/twig-bridge/Extension/TranslationExtension.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/twig-bridge/Extension/AssetExtension.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/asset/Packages.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/asset/PackageInterface.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/asset/Package.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/asset/PathPackage.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/asset/VersionStrategy/VersionStrategyInterface.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/asset/VersionStrategy/StaticVersionStrategy.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/asset/Context/ContextInterface.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/asset/Context/RequestStackContext.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/twig-bridge/Extension/CodeExtension.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/twig-bridge/Extension/RoutingExtension.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/twig-bridge/Extension/YamlExtension.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/twig-bridge/Extension/StopwatchExtension.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/twig-bridge/Extension/ExpressionExtension.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/twig-bridge/Extension/HttpKernelExtension.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/twig-bridge/Extension/HttpFoundationExtension.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/http-foundation/UrlHelper.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/twig-bridge/Extension/FormExtension.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/twig-bridge/Extension/LogoutUrlExtension.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/twig-bridge/Extension/SecurityExtension.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/security-http/Impersonate/ImpersonateUrlGenerator.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/twig/twig/src/Extension/GlobalsInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Twig/TwigExtension.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/doctrine/doctrine-bundle/Twig/DoctrineExtension.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/jms/serializer/src/Twig/SerializerBaseExtension.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/jms/serializer/src/Twig/SerializerRuntimeExtension.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/nelmio/api-doc-bundle/Render/Html/GetNelmioAsset.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/twig/markdown-extra/MarkdownExtension.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/twig/string-extra/StringExtension.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/sentry/sentry-symfony/src/Tracing/Twig/TwigTracingExtension.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/sentry/sentry-symfony/src/Twig/SentryExtension.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/twig-bridge/AppVariable.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/twig/twig/src/RuntimeLoader/RuntimeLoaderInterface.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/twig/twig/src/RuntimeLoader/ContainerRuntimeLoader.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/twig-bundle/DependencyInjection/Configurator/EnvironmentConfigurator.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/http-kernel/Debug/FileLinkFormatter.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/stopwatch/Stopwatch.php';

        $a = new \Twig\Loader\FilesystemLoader([], \dirname(__DIR__, 4));
        $a->addPath((\dirname(__DIR__, 5).'/lib/vendor/doctrine/doctrine-bundle/Resources/views'), 'Doctrine');
        $a->addPath((\dirname(__DIR__, 5).'/lib/vendor/doctrine/doctrine-bundle/Resources/views'), '!Doctrine');
        $a->addPath((\dirname(__DIR__, 5).'/lib/vendor/jms/serializer-bundle/Resources/views'), 'JMSSerializer');
        $a->addPath((\dirname(__DIR__, 5).'/lib/vendor/jms/serializer-bundle/Resources/views'), '!JMSSerializer');
        $a->addPath((\dirname(__DIR__, 4).'/templates/bundles/NelmioApiDocBundle'), 'NelmioApiDoc');
        $a->addPath((\dirname(__DIR__, 5).'/lib/vendor/nelmio/api-doc-bundle/Resources/views'), 'NelmioApiDoc');
        $a->addPath((\dirname(__DIR__, 5).'/lib/vendor/nelmio/api-doc-bundle/Resources/views'), '!NelmioApiDoc');
        $a->addPath((\dirname(__DIR__, 4).'/templates/bundles/TwigBundle'), 'Twig');
        $a->addPath((\dirname(__DIR__, 4).'/templates/bundles/TwigBundle'), '!Twig');
        $a->addPath((\dirname(__DIR__, 5).'/lib/vendor/symfony/security-bundle/Resources/views'), 'Security');
        $a->addPath((\dirname(__DIR__, 5).'/lib/vendor/symfony/security-bundle/Resources/views'), '!Security');
        $a->addPath((\dirname(__DIR__, 5).'/lib/vendor/doctrine/doctrine-migrations-bundle/Resources/views'), 'DoctrineMigrations');
        $a->addPath((\dirname(__DIR__, 5).'/lib/vendor/doctrine/doctrine-migrations-bundle/Resources/views'), '!DoctrineMigrations');
        $a->addPath((\dirname(__DIR__, 4).'/templates'));
        $a->addPath((\dirname(__DIR__, 5).'/lib/vendor/symfony/twig-bridge/Resources/views/Form'));

        $container->services['.container.private.twig'] = $instance = new \Twig\Environment($a, ['debug' => false, 'strict_variables' => false, 'autoescape' => 'name', 'cache' => ($container->targetDir.''.'/twig'), 'charset' => 'UTF-8']);

        $b = ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()));
        $c = ($container->privates['router.request_context'] ?? $container->getRouter_RequestContextService());

        $d = new \Symfony\Bridge\Twig\Extension\AssetExtension(new \Symfony\Component\Asset\Packages(new \Symfony\Component\Asset\PathPackage('', new \Symfony\Component\Asset\VersionStrategy\StaticVersionStrategy('v=8.1.3', '%s?%s'), new \Symfony\Component\Asset\Context\RequestStackContext($b, $c->getBaseUrl(), $c->isSecure())), new RewindableGenerator(function () use ($container) {
            return new \EmptyIterator();
        }, 0)));
        $e = ($container->services['.container.private.security.authorization_checker'] ?? $container->get_Container_Private_Security_AuthorizationCheckerService());
        $f = ($container->services['.container.private.security.token_storage'] ?? $container->get_Container_Private_Security_TokenStorageService());
        $g = ($container->privates['Sentry\\State\\HubInterface'] ?? $container->getHubInterfaceService());
        $h = new \Symfony\Bridge\Twig\AppVariable();
        $h->setEnvironment('prod');
        $h->setDebug(false);
        if ($container->has('.container.private.security.token_storage')) {
            $h->setTokenStorage($f);
        }
        if ($container->has('request_stack')) {
            $h->setRequestStack($b);
        }

        $instance->addExtension(new \Symfony\Bridge\Twig\Extension\CsrfExtension());
        $instance->addExtension(new \Symfony\Bridge\Twig\Extension\TranslationExtension(NULL));
        $instance->addExtension($d);
        $instance->addExtension(new \Symfony\Bridge\Twig\Extension\CodeExtension(($container->privates['debug.file_link_formatter'] ?? ($container->privates['debug.file_link_formatter'] = new \Symfony\Component\HttpKernel\Debug\FileLinkFormatter(NULL))), \dirname(__DIR__, 4), 'UTF-8'));
        $instance->addExtension(new \Symfony\Bridge\Twig\Extension\RoutingExtension(($container->services['router'] ?? $container->getRouterService())));
        $instance->addExtension(new \Symfony\Bridge\Twig\Extension\YamlExtension());
        $instance->addExtension(new \Symfony\Bridge\Twig\Extension\StopwatchExtension(($container->privates['debug.stopwatch'] ?? ($container->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))), false));
        $instance->addExtension(new \Symfony\Bridge\Twig\Extension\ExpressionExtension());
        $instance->addExtension(new \Symfony\Bridge\Twig\Extension\HttpKernelExtension());
        $instance->addExtension(new \Symfony\Bridge\Twig\Extension\HttpFoundationExtension(new \Symfony\Component\HttpFoundation\UrlHelper($b, $c)));
        $instance->addExtension(new \Symfony\Bridge\Twig\Extension\FormExtension(NULL));
        $instance->addExtension(new \Symfony\Bridge\Twig\Extension\LogoutUrlExtension(($container->privates['security.logout_url_generator'] ?? $container->getSecurity_LogoutUrlGeneratorService())));
        $instance->addExtension(new \Symfony\Bridge\Twig\Extension\SecurityExtension($e, new \Symfony\Component\Security\Http\Impersonate\ImpersonateUrlGenerator($b, ($container->privates['security.firewall.map'] ?? $container->getSecurity_Firewall_MapService()), $f)));
        $instance->addExtension(new \App\Twig\TwigExtension(($container->privates['App\\Service\\DOMJudgeService'] ?? $container->getDOMJudgeServiceService()), ($container->services['App\\Service\\ConfigurationService'] ?? $container->getConfigurationServiceService()), $instance, ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['App\\Service\\SubmissionService'] ?? $container->load('getSubmissionServiceService')), ($container->privates['App\\Service\\EventLogService'] ?? $container->load('getEventLogServiceService')), $f, $e, \dirname(__DIR__, 4)));
        $instance->addExtension(new \Doctrine\Bundle\DoctrineBundle\Twig\DoctrineExtension());
        $instance->addExtension(new \JMS\Serializer\Twig\SerializerRuntimeExtension('jms_'));
        $instance->addExtension(new \Nelmio\ApiDocBundle\Render\Html\GetNelmioAsset($d));
        $instance->addExtension(new \Twig\Extra\Markdown\MarkdownExtension());
        $instance->addExtension(new \Twig\Extra\String\StringExtension());
        $instance->addExtension(new \Sentry\SentryBundle\Tracing\Twig\TwigTracingExtension($g));
        $instance->addExtension(new \Sentry\SentryBundle\Twig\SentryExtension($g));
        $instance->addGlobal('app', $h);
        $instance->addRuntimeLoader(new \Twig\RuntimeLoader\ContainerRuntimeLoader(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'JMS\\Serializer\\Twig\\SerializerRuntimeHelper' => ['privates', 'jms_serializer.twig_extension.serializer_runtime_helper', 'getJmsSerializer_TwigExtension_SerializerRuntimeHelperService', true],
            'Symfony\\Bridge\\Twig\\Extension\\CsrfRuntime' => ['privates', 'twig.runtime.security_csrf', 'getTwig_Runtime_SecurityCsrfService', true],
            'Symfony\\Bridge\\Twig\\Extension\\HttpKernelRuntime' => ['privates', 'twig.runtime.httpkernel', 'getTwig_Runtime_HttpkernelService', true],
            'Symfony\\Component\\Form\\FormRenderer' => ['privates', 'twig.form.renderer', 'getTwig_Form_RendererService', true],
            'Twig\\Extra\\Markdown\\MarkdownRuntime' => ['privates', 'twig.runtime.markdown', 'getTwig_Runtime_MarkdownService', true],
        ], [
            'JMS\\Serializer\\Twig\\SerializerRuntimeHelper' => '?',
            'Symfony\\Bridge\\Twig\\Extension\\CsrfRuntime' => '?',
            'Symfony\\Bridge\\Twig\\Extension\\HttpKernelRuntime' => '?',
            'Symfony\\Component\\Form\\FormRenderer' => '?',
            'Twig\\Extra\\Markdown\\MarkdownRuntime' => '?',
        ])));
        $instance->addGlobal('DOMJUDGE_VERSION', '8.1.3');
        $instance->addGlobal('DJ_CHARACTER_SET', 'utf-8');
        $instance->addGlobal('teamname_max_length', 30);
        (new \Symfony\Bundle\TwigBundle\DependencyInjection\Configurator\EnvironmentConfigurator('F j, Y H:i', '%d days', NULL, 0, '.', ','))->configure($instance);

        return $instance;
    }
}
