<?php

namespace ContainerU4tLbsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X05SDiService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.X05S_di' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.X05S_di'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'eventLogService' => ['privates', 'App\\Service\\EventLogService', 'getEventLogServiceService', true],
            'scoreboardService' => ['privates', 'App\\Service\\ScoreboardService', 'getScoreboardServiceService', true],
        ], [
            'eventLogService' => 'App\\Service\\EventLogService',
            'scoreboardService' => 'App\\Service\\ScoreboardService',
        ]);
    }
}
