<?php

namespace ContainerU4tLbsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnalysisControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Jury\AnalysisController' shared autowired service.
     *
     * @return \App\Controller\Jury\AnalysisController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Jury/AnalysisController.php';

        $container->services['App\\Controller\\Jury\\AnalysisController'] = $instance = new \App\Controller\Jury\AnalysisController(($container->privates['App\\Service\\DOMJudgeService'] ?? $container->getDOMJudgeServiceService()), ($container->privates['App\\Service\\StatisticsService'] ?? $container->load('getStatisticsServiceService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));

        $instance->setContainer(($container->privates['.service_locator.Qhw4Z9B'] ?? $container->load('get_ServiceLocator_Qhw4Z9BService'))->withContext('App\\Controller\\Jury\\AnalysisController', $container));

        return $instance;
    }
}
