<?php

namespace ContainerU4tLbsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBalloonServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\BalloonService' shared autowired service.
     *
     * @return \App\Service\BalloonService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/BalloonService.php';

        return $container->privates['App\\Service\\BalloonService'] = new \App\Service\BalloonService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->services['App\\Service\\ConfigurationService'] ?? $container->getConfigurationServiceService()));
    }
}
