<?php

namespace ContainerU4tLbsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCache_AppService extends App_KernelProdContainer
{
    /*
     * Gets the public 'cache.app' shared service.
     *
     * @return \Sentry\SentryBundle\Tracing\Cache\TraceableCacheAdapter
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = new \Symfony\Component\Cache\Adapter\FilesystemAdapter('0-YN7RAcc5', 0, ($container->targetDir.''.'/pools/app'), ($container->privates['cache.default_marshaller'] ?? ($container->privates['cache.default_marshaller'] = new \Symfony\Component\Cache\Marshaller\DefaultMarshaller(NULL, false))));
        $a->setLogger(($container->privates['monolog.logger.cache'] ?? $container->getMonolog_Logger_CacheService()));

        return $container->services['cache.app'] = new \Sentry\SentryBundle\Tracing\Cache\TraceableCacheAdapter(($container->privates['Sentry\\State\\HubInterface'] ?? $container->getHubInterfaceService()), $a);
    }
}
