<?php

namespace ContainerU4tLbsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsole_Command_CachePoolPruneService extends App_KernelProdContainer
{
    /*
     * Gets the private 'console.command.cache_pool_prune' shared service.
     *
     * @return \Symfony\Bundle\FrameworkBundle\Command\CachePoolPruneCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/framework-bundle/Command/CachePoolPruneCommand.php';

        $container->privates['console.command.cache_pool_prune'] = $instance = new \Symfony\Bundle\FrameworkBundle\Command\CachePoolPruneCommand(new RewindableGenerator(function () use ($container) {
            yield 'cache.validator.traceable' => ($container->privates['cache.validator.traceable'] ?? $container->load('getCache_Validator_TraceableService'));
            yield 'cache.annotations.traceable' => ($container->privates['cache.annotations.traceable'] ?? $container->getCache_Annotations_TraceableService());
            yield 'cache.property_info.traceable' => ($container->privates['cache.property_info.traceable'] ?? $container->load('getCache_PropertyInfo_TraceableService'));
            yield 'doctrine.result_cache_pool.traceable' => ($container->privates['doctrine.result_cache_pool.traceable'] ?? $container->getDoctrine_ResultCachePool_TraceableService());
            yield 'doctrine.system_cache_pool.traceable' => ($container->privates['doctrine.system_cache_pool.traceable'] ?? $container->getDoctrine_SystemCachePool_TraceableService());
            yield 'cache.property_access.traceable' => ($container->privates['cache.property_access.traceable'] ?? $container->load('getCache_PropertyAccess_TraceableService'));
            yield 'cache.security_expression_language.traceable' => ($container->privates['cache.security_expression_language.traceable'] ?? $container->load('getCache_SecurityExpressionLanguage_TraceableService'));
            yield 'cache.app' => ($container->services['cache.app'] ?? $container->load('getCache_AppService'));
            yield 'cache.system' => ($container->services['cache.system'] ?? $container->load('getCache_SystemService'));
            yield 'cache.validator_expression_language' => ($container->services['cache.validator_expression_language'] ?? $container->load('getCache_ValidatorExpressionLanguageService'));
        }, 10));

        $instance->setName('cache:pool:prune');
        $instance->setDescription('Prune cache pools');

        return $instance;
    }
}
