<?php

namespace ContainerU4tLbsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCache_PropertyAccess_TraceableService extends App_KernelProdContainer
{
    /*
     * Gets the private 'cache.property_access.traceable' shared service.
     *
     * @return \Sentry\SentryBundle\Tracing\Cache\TraceableCacheAdapter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/property-access/PropertyAccessorInterface.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/property-access/PropertyAccessor.php';

        return $container->privates['cache.property_access.traceable'] = new \Sentry\SentryBundle\Tracing\Cache\TraceableCacheAdapter(($container->privates['Sentry\\State\\HubInterface'] ?? $container->getHubInterfaceService()), \Symfony\Component\PropertyAccess\PropertyAccessor::createCache('F-19oYj7zG', 0, $container->getParameter('container.build_id'), ($container->privates['monolog.logger.cache'] ?? $container->getMonolog_Logger_CacheService())));
    }
}
