<?php

namespace ContainerU4tLbsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConstraintViolationListInterfaceService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.F_AUBeP.Symfony\Component\Validator\ConstraintViolationListInterface' shared service.
     *
     * @return \Symfony\Component\Validator\ConstraintViolationListInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.F_AUBeP": it references interface "Symfony\\Component\\Validator\\ConstraintViolationListInterface" but no such service exists. Did you create a class that implements this interface?');
    }
}
