<?php

namespace ContainerU4tLbsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContestService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.E0Dj3BT.App\Entity\Contest' shared service.
     *
     * @return \App\Entity\Contest
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.E0Dj3BT": it references class "App\\Entity\\Contest" but no such service exists.');
    }
}
