<?php

namespace ContainerU4tLbsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsoleListenerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'Sentry\SentryBundle\EventListener\ConsoleListener' shared service.
     *
     * @return \Sentry\SentryBundle\EventListener\ConsoleListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/lib/vendor/sentry/sentry-symfony/src/EventListener/ConsoleListener.php';

        return $container->privates['Sentry\\SentryBundle\\EventListener\\ConsoleListener'] = new \Sentry\SentryBundle\EventListener\ConsoleListener(($container->privates['Sentry\\State\\HubInterface'] ?? $container->getHubInterfaceService()), true);
    }
}
