<?php

namespace ContainerU4tLbsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDOMJudgeXHeadersAuthenticatorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Security\DOMJudgeXHeadersAuthenticator' shared autowired service.
     *
     * @return \App\Security\DOMJudgeXHeadersAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/security-http/Authenticator/AuthenticatorInterface.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/security-http/Authenticator/AbstractAuthenticator.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/security-http/EntryPoint/AuthenticationEntryPointInterface.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/security-http/Util/TargetPathTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Security/DOMJudgeXHeadersAuthenticator.php';

        return $container->privates['App\\Security\\DOMJudgeXHeadersAuthenticator'] = new \App\Security\DOMJudgeXHeadersAuthenticator(($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')), ($container->privates['security.user.provider.concrete.domjudge_db_provider'] ?? $container->load('getSecurity_User_Provider_Concrete_DomjudgeDbProviderService')), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')), ($container->services['App\\Service\\ConfigurationService'] ?? $container->getConfigurationServiceService()), ($container->services['router'] ?? $container->getRouterService()));
    }
}
