<?php

namespace ContainerU4tLbsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExternalJudgementService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.UvovWc4.App\Entity\ExternalJudgement' shared service.
     *
     * @return \App\Entity\ExternalJudgement
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.UvovWc4": it references class "App\\Entity\\ExternalJudgement" but no such service exists.');
    }
}
