<?php

namespace ContainerU4tLbsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExternalContestSourceServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\ExternalContestSourceService' shared autowired service.
     *
     * @return \App\Service\ExternalContestSourceService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/ExternalContestSourceService.php';

        return $container->privates['App\\Service\\ExternalContestSourceService'] = new \App\Service\ExternalContestSourceService(($container->privates['http_client'] ?? $container->load('getHttpClientService')), ($container->privates['App\\Service\\DOMJudgeService'] ?? $container->getDOMJudgeServiceService()), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->services['monolog.logger.event-feed-importer'] ?? $container->load('getMonolog_Logger_EventfeedimporterService')), ($container->services['App\\Service\\ConfigurationService'] ?? $container->getConfigurationServiceService()), ($container->privates['App\\Service\\EventLogService'] ?? $container->load('getEventLogServiceService')), ($container->privates['App\\Service\\SubmissionService'] ?? $container->load('getSubmissionServiceService')), ($container->privates['App\\Service\\ScoreboardService'] ?? $container->load('getScoreboardServiceService')));
    }
}
