<?php

namespace ContainerU4tLbsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJsonImportTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\Type\JsonImportType' shared autowired service.
     *
     * @return \App\Form\Type\JsonImportType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Type/JsonImportType.php';

        return $container->privates['App\\Form\\Type\\JsonImportType'] = new \App\Form\Type\JsonImportType();
    }
}
