<?php

namespace ContainerU4tLbsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJudging2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.Uh_XD.d.App\Entity\Judging' shared service.
     *
     * @return \App\Entity\Judging
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Uh_XD.d": it references class "App\\Entity\\Judging" but no such service exists.');
    }
}
