<?php

namespace ContainerU4tLbsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoadDefaultDataCommandService extends App_KernelProdContainer
{
    /*
     * Gets the public 'console.command.public_alias.App\Command\LoadDefaultDataCommand' shared autowired service.
     *
     * @return \App\Command\LoadDefaultDataCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/LoadDefaultDataCommand.php';

        return $container->services['console.command.public_alias.App\\Command\\LoadDefaultDataCommand'] = new \App\Command\LoadDefaultDataCommand();
    }
}
