<?php

namespace ContainerU4tLbsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProblemTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\Type\ProblemType' shared autowired service.
     *
     * @return \App\Form\Type\ProblemType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Type/AbstractExternalIdEntityType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Type/ProblemType.php';

        return $container->privates['App\\Form\\Type\\ProblemType'] = new \App\Form\Type\ProblemType(($container->privates['App\\Service\\EventLogService'] ?? $container->load('getEventLogServiceService')));
    }
}
