<?php

namespace ContainerU4tLbsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProblemUploadTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\Type\ProblemUploadType' shared autowired service.
     *
     * @return \App\Form\Type\ProblemUploadType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Type/ProblemUploadType.php';

        return $container->privates['App\\Form\\Type\\ProblemUploadType'] = new \App\Form\Type\ProblemUploadType();
    }
}
