<?php

namespace ContainerU4tLbsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRejudgingServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\RejudgingService' shared autowired service.
     *
     * @return \App\Service\RejudgingService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/RejudgingService.php';

        return $container->privates['App\\Service\\RejudgingService'] = new \App\Service\RejudgingService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['App\\Service\\DOMJudgeService'] ?? $container->getDOMJudgeServiceService()), ($container->privates['App\\Service\\ScoreboardService'] ?? $container->load('getScoreboardServiceService')), ($container->privates['App\\Service\\EventLogService'] ?? $container->load('getEventLogServiceService')), ($container->privates['App\\Service\\BalloonService'] ?? $container->load('getBalloonServiceService')));
    }
}
