<?php

namespace ContainerU4tLbsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScoreboardController2Service extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Jury\ScoreboardController' shared autowired service.
     *
     * @return \App\Controller\Jury\ScoreboardController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Jury/ScoreboardController.php';

        $container->services['App\\Controller\\Jury\\ScoreboardController'] = $instance = new \App\Controller\Jury\ScoreboardController(($container->privates['App\\Service\\DOMJudgeService'] ?? $container->getDOMJudgeServiceService()), ($container->privates['App\\Service\\ScoreboardService'] ?? $container->load('getScoreboardServiceService')));

        $instance->setContainer(($container->privates['.service_locator.Qhw4Z9B'] ?? $container->load('get_ServiceLocator_Qhw4Z9BService'))->withContext('App\\Controller\\Jury\\ScoreboardController', $container));

        return $instance;
    }
}
