<?php

namespace ContainerU4tLbsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTeamAffiliationTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\Type\TeamAffiliationType' shared autowired service.
     *
     * @return \App\Form\Type\TeamAffiliationType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Type/AbstractExternalIdEntityType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Type/TeamAffiliationType.php';

        return $container->privates['App\\Form\\Type\\TeamAffiliationType'] = new \App\Form\Type\TeamAffiliationType(($container->privates['App\\Service\\EventLogService'] ?? $container->load('getEventLogServiceService')), ($container->services['App\\Service\\ConfigurationService'] ?? $container->getConfigurationServiceService()), ($container->privates['App\\Service\\DOMJudgeService'] ?? $container->getDOMJudgeServiceService()));
    }
}
